import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { headers } from 'next/headers';
import { Header } from '@/components/core/header';
import { Footer } from '@/components/core/footer';
import { BlockProvider } from '@/components/providers/block';
import { Toaster } from '@/components/ui/sonner';
import { AbstractWalletWrapper } from '@/components/providers/abstract';
import MatrixRainBackground from '@/components/background';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerStore = await headers();
  const nonce = headerStore.get('x-nonce') ?? undefined;

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AbstractWalletWrapper nonce={nonce}>
          <BlockProvider>
            <Header />
            <div className="relative -mt-16 flex flex-col overflow-hidden lg:min-h-screen lg:pt-16">
              <MatrixRainBackground />
              {children}
            </div>
          </BlockProvider>
          <Footer />
        </AbstractWalletWrapper>
        <Toaster />
      </body>
    </html>
  );
}
